<!DOCTYPE html>
<head>
	<title>MVC demo-site</title>
	<link href="css/site.css" rel="stylesheet" type="text/css">
	<?= $this->getCss() ?>

	<style type="text/css">
		article {
			width:            600px; heigth: 500px;
			min-height:       400px;
			background-color: #92b6dc;
			margin:           auto;
		}
	</style>
    <?= $this->getCss() ?>
</head>
<body bgcolor="#c0c0c0">
	<h2>MVC demo-site ++ default</h2>
	<a href="index.php?controller=articles&action=index">articles index</a> |
	<a href="index.php?controller=gallery&action=show">articles gallery</a> |
    <a href="index.php?controller=articles&action=home">articles home</a> |
    <a href="index.php?controller=articles&action=add">articles add</a> |
	<hr>
    <article>
	<?= $this->getView()  ?>
    </article>
	<p class="author">me</p>
</body>