<h3>
    <?= $view->title ?> ADD
</h3>
<br>
<a href="index.php?controller=articles&action=index">articles index</a><br>
<a href="index.php?controller=articles&action=show">articles show</a><br>
<a href="index.php?controller=articles&action=add">articles add</a><br>
<a href="index.php?controller=articles&action=show">articles show</a><br>
<hr>
<?= $view->string ?><br>
<?php print_r($view->data); ?>



